#!/usr/bin/python3
# -*- coding: utf-8 -*-
"""
DB Reborn 1.0.0 - GUI
Dragonbones to Spine Converter
For use in Defold Extension-Spine 3.6.5
and other Game Engines
Compatible with Spine 4.2.22
"""

import json
from PIL import Image
import os.path
import sys
from pathlib import Path
import shutil

"""
############################# BEGIN OF FUNCTIONS THAT CALC BEZIER CURVE #################################
"""

def bezier_curve_calc_begin_values(ini_value, last_value, vector):
    # Formula for Values (X1 and Y1) in the 'curve' list
    result = ini_value + ((last_value - ini_value) * vector)
    return result

def bezier_curve_calc_end_values_x(ini_value, last_value, vector):
    # Formula for Values (X1 and Y1) in the 'curve' list
    result = last_value - ((last_value - ini_value) * vector)
    return result

def bezier_curve_calc_end_values_y(last_value, vector):
    # Formula for Values (X2 and Y2) in the 'curve' list
    result = last_value * vector
    return result

def convertion_completed(value):
    conv_completed = value
    return conv_completed


"""
############################# END OF FUNCTIONS THAT CALC BEZIER CURVE #################################
"""

"""
### BEGIN DB CHECK - CHECK IF JSON WAS GENERATED FROM DRAGONBONES AND THERE'S AN FOLDER WITH IMAGES ###
"""
class DbJsonCheck:
    def __init__(self, json_file):
        self.json_file = json_file
        self.json_state = False
        self.texture_folder_in_place = False
        self.images_in_texture_folder = False

        #print(self.json_file)
        self.basic_key_pattern_list_json = ['skeleton', 'bones', 'slots', 'skins', 'animations']
        self.dict_json_keys = {'animations', 'skins', 'bones', 'skeleton', 'slots'}
        self.json_keys = []

        # Get the Texture Images Folder Path, using the JSON File Name
        #self.images_directory_path = os.path.dirname(os.path.abspath(__file__))
        self.images_directory_path = os.path.dirname(self.json_file)
        # print(self.images_directory_path)

        filename_path = Path(self.json_file)
        self.texture_folder_name = filename_path.stem + "_texture"
        # print(self.texture_folder_name)

        # Create a var with the Texture folder that must be generated by DragonBones
        self.images_folder = (self.images_directory_path + "/" + self.texture_folder_name)
        #print(self.images_folder)

        # Check if Json is OK
        self.check_json()

    def check_json(self):
        #print("check active")
        # Open Json
        try:
            with (open(self.json_file, 'r') as file_check):
                self.json_data_check = json.load(file_check)  # The json we will check if it has the minimum arguments
            # Create a list of Json keys
            for key_to_check in self.json_data_check:
                #print(key_to_check)
                self.json_keys.append(key_to_check)
            #print(self.basic_key_pattern_list_json, self.json_keys)
            #print(set(self.basic_key_pattern_list_json).intersection(self.json_keys))
            if set(self.basic_key_pattern_list_json).intersection(self.json_keys) == self.dict_json_keys:
                self.json_state = True
                #After Json is OK, proceed to check the Images Folder
                self.check_images_folder()
            else:
                self.json_state = False
            #print(self.json_state)
        except:
            self.json_state = False

    def check_images_folder(self):
        # Check if there's an image folder with the same name of Json file
        # Check if it's a directory
        if os.path.isdir(self.images_folder):
            # Is there's a folder named with the same name os JSON, proceed
            self.texture_folder_in_place = True

            # Looking for images inside the Texture Folder
            #image_extensions = ('.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff', '.webp', '.svg')
            images_extensions = ('*.jpg', '*.jpeg', '*.png', '*.gif', '*.bmp', '*.tiff', '*.webp', '*.svg', '*.PNG')

            root_path = Path(self.images_folder)
            # print(root_path)

            #Create a list of all images in the json slots
            image_files_in_json = set()
            for skin_name in self.json_data_check['skins']:
                #print(skin_name)
                #print(self.json_data_check['skins'][skin_name])
                for element in self.json_data_check['skins'][skin_name]:
                    #print(element)
                    for bone in self.json_data_check['skins'][skin_name][element]:
                        if os.sep in bone:
                            #print(os.path.basename(slot['attachment']))
                            image_files_in_json.add(Path(bone).stem)
                        else:
                            image_files_in_json.add(Path(bone).stem)

            #print(len(image_files_in_json))
            #print(image_files_in_json)

            #Looking for the images in the folder to match
            image_files = set()
            for ext in images_extensions:
                # rglob recursively searches for files matching the pattern
                for image_path in root_path.rglob(ext):
                    image_with_extension = os.path.basename(image_path)
                    image_name = os.path.splitext(image_with_extension)[0]
                    image_files.add(image_name)
            #print(len(image_files))
            #print(image_files)

            #Match the 2 lists to complete the check
            matches_comprehension = [element for element in image_files_in_json if element in image_files ]
            #print(len(matches_comprehension))

            # If the directory is not empty (images inside) proceed
            if image_files: # If there's image files in texture folder
                #print("Images located")
                # If the image number are equal in json and in texture folder
                if len(image_files_in_json) == len(image_files):
                    if len(matches_comprehension) == len(image_files_in_json):
                        self.images_in_texture_folder = True
                        #print("Images match!")
                    else:
                        self.images_in_texture_folder = False
                else:
                    self.images_in_texture_folder = False
                    #print("Images not match!")
            # If the directory is empty
            else:
                self.images_in_texture_folder = False
        else:
            # print(f"The folder '{self.images_folder}' does not exist.")
            self.texture_folder_in_place = False


"""
###################### END OF DB CHECK - CHECK IF JSON WAS GENERATED FROM DRAGONBONES ##########################
"""

"""
###################################### BEGIN OF SCRIPT PROCESS #############################################
"""
class DbJsonConverter:
    global textures_folder_name
    def __init__(self, old_json_file_name, new_json_file, spine_version, easing_type, copy_textures_folder):
        self.old_json_file_name = old_json_file_name
        self.new_json_file = new_json_file
        self.spine_version = spine_version
        self.easing_type = easing_type
        self.copy_textures_folder = copy_textures_folder
        self.file_converted = False
        self.conversion()

        # Errors Vars#
        self.db_error = False # When occur error
        self.db_error_type = "" # Error type message

    def conversion(self):
        #print(self.old_json_file_name)
        # Open and read the JSON file
        with open(self.old_json_file_name, 'r') as file:
            json_data = json.load(file) # The json we will work

        with open(self.old_json_file_name, 'r') as file_old:
            old_json_data = json.load(file_old)  # The json we will get old curve data

        # Add Spine Version to the file
        json_data['skeleton']['spine'] = self.spine_version
        # print(json_data['skeleton'])

        # Add argument "order" to the bones. The base bone stay without it
        # print(len(json_data['ik']))
        if 'ik' in json_data:
            ik_len = len(json_data['ik'])
            #print(ik_len, json_data['ik'][0]['bones'][0][-1])
            for number in reversed(range(ik_len)):
                if number == 0:
                    continue
                #print(json_data['ik'][number]['bones'][0][-1])
                json_data['ik'][number]['order'] = number

        # Change skins section to a new configuration
        new_skins_structure = [{'name': 'default', 'attachments':{}}]
        # print(len(json_data['skins']['default']))

        # Copy Default Skins to the Attachments Dict
        new_skins_structure[0]['attachments'].update(json_data['skins']['default'])
        #print(new_skins_structure)

        #Replacing Skins Section to new_skins_structure
        json_data['skins'] = new_skins_structure
        skins_attachments = json_data['skins'][0]['attachments']
        # print(json_data['skins'])

        # Add Skins Keys into a dictionary with number of dictionaries inside each one
        skins_keys = {}
        list_of_skins = []
        for key in skins_attachments:
            skins_keys[key] = skins_attachments[key]
        #print(skins_keys)
        for k, v in skins_keys.items():
            #del values["name"]
            #print(k, v)
            for key, values in v.items():
                # Removing the Key "Name" -> It's not necessary
                # del values["name"]
                #print(key, values)
                list_of_skins.append(values)
        #print(list_of_skins)

        # Get the list of images in image folder
        path = self.old_json_file_name[:-5] + "_texture/"

        images_extensions = ('*.jpg', '*.jpeg', '*.png', '*.gif', '*.bmp', '*.tiff', '*.webp', '*.svg', '*.PNG' )
        root_path = Path(path)
        #print(root_path)

        image_files = []
        image_roots = []
        for ext in images_extensions:
            # rglob recursively searches for files matching the pattern
            for image_path in root_path.rglob(ext):
                # Get the root of each image
                img = image_path.resolve().parent
                image_roots.append(img)
                # Get the list of each image
                image_files.append(image_path)
        #print(image_files) # Full Path where image is
        #print(image_roots) # Full path to the folder where image is

        imgs = []
        valid_images = [".jpg",".gif",".png",".tga"]

        slot_list_master = []
        if 'slots' in json_data:
            for key in json_data["slots"]:
                slot_list_master.append(key)
        #print(slot_list_master)

        slot_dict = {}
        slot_list = []
        # If there's SLOT section in Animations:
        if 'animations' in json_data:
            #print(json_data["animations"])
            for anim_key in json_data["animations"]:
                #print(anim_key)
                #print(json_data["animations"][anim_key].items())
                #print(json_data["animations"][anim_key])
                #print(type(anim_key))
                slot_list.append(json_data["animations"][anim_key]['slots'])
                #print(slot_list)
                # If there Slot Key, proceed
                if json_data["animations"][anim_key]['slots']:
                    #print(json_data["animations"][anim_key]['slots'])
                    for slot_keys in json_data["animations"][anim_key]['slots']:
                        slot_dict = json_data["animations"][anim_key]['slots'][slot_keys]
                        #print(json_data["animations"][anim_key]['slots'][slot_keys].items())
                        for key in list(json_data["animations"][anim_key]['slots'][slot_keys]):
                            #print(key, slot_dict)
                            # If there's 'color', replace for 'rgba'
                            if key == 'color':
                                # print(slot_dict)
                                slot_dict.update({'rgba': slot_dict.pop('color')})

        #print(slot_list)
        for item in slot_list: # Get each item of the list
            #print(item)
            for element_key, element_value in item.items(): # Get the values inside the key
                #print(element_key, element_value)
                for key in list(element_value):
                    #print(key)
                    if key != "attachment":
                        #print(element_key)
                        # Add a key 'attachment' and the correspondent attachment
                        # in the dict that doesn't have it
                        for element in slot_list_master:
                            #print(element_key)
                            if element["name"] == element_key:
                                #print(element["attachment"])
                                element_value['attachment'] = [{"name": element["attachment"] }]

        for path_root in image_roots:
            #print(path_root)
            #print(os.path.basename(path_root))
            for file_name in os.listdir(path_root):
                try:
                    #print(file_name)
                    # Extension of image file
                    ext = os.path.splitext(file_name)[1]
                    # Get Each image name in Texture Folder without extension to use in the skins structure
                    image_name = os.path.splitext(file_name)[0]
                    #print(image_name)

                    image_size = Image.open(f"{path_root}/{file_name}")
                    #print(image_size.width, image_size.height)
                    folder_name = os.path.basename(path_root)
                    #print(folder_name)
                    image_size.close()

                except:
                    pass

                # Compare Images in Folder and add Width and Height for each image in Skins Section
                for key in list_of_skins:
                    if image_name != key['name']:
                        # If the images are inside a folder YOUR_CHARACTER_Texture, erase all path names
                        original_string = key['name']
                        #print(original_string)
                        file_name_string = os.path.basename(original_string)
                        #print(file_name_string)
                        key['name'] = file_name_string

                    if image_name == key['name']:
                        # print(image_name, key)
                        # Add Width and Height for each image
                        key.update(width=image_size.width)
                        key.update(height=image_size.height)

                # print(image_name, type(image_name))
                # print(image_size.width, image_size.height, type(image_size.width), type(image_size.height))

                # If the extension is not in valid images, then exit
                if ext.lower() not in valid_images:
                    continue
                with Image.open(os.path.join(path_root,file_name)) as img:
                    imgs.append(img)


        temp_json_data = json_data  # Create a copy o json_data to work with
        old_temp_json_data = old_json_data # Make a copy to get the old curve values
        #print(temp_json_data)


        """
        ########################### ANIMATION SECTION ##################################
        
        ######################### BEGIN OF CURVE SECTION ###############################
        
        """
        if self.easing_type == 'curve':
            #print("Easy Type: Curve")
            #ROTATE Vars
            time_value_data_rotate = []
            db_time_value_data_rotate = []
            counter = 0
            step_curve = 0
            ini_value_original = 0

            # TRANSLATE Vars
            db_time_value_data_translate = []
            db_time_data_translate = []
            xy_data = []
            time_counter = 0
            time_counter_xy = 0
            counter_translate = 0
            temp_curve = []
            ini_value_original_x = 0
            ini_value_original_y = 0

            # SCALE Vars
            db_time_value_data_scale = []
            db_time_data_scale = []
            xy_data_scale = []
            time_counter_scale = 0
            time_counter_xy_scale = 0
            counter_scale = 0
            temp_curve_scale = []
            ini_value_original_x_scale = 0
            ini_value_original_y_scale = 0

            # SLOTS Vars
            db_time_value_data_slot = []
            db_time_data_slot = []
            color_data_slot = []
            attrib_slot_color = []
            time_counter_slot_color = 0
            time_counter_curve_color = 0

            # This part gets the info of curve Vectors from de Old Dragonbones Json and put into a List
            # Loop in Animation Keys
            for anim_key_old in old_temp_json_data["animations"]:
                #print(anim_key_old)
                for bone_key_old in old_temp_json_data["animations"][anim_key_old]["bones"]:
                    attributes_old = old_temp_json_data["animations"][anim_key_old]["bones"][bone_key_old]
                    # Detecting if there's specific animation attributes in the Json
                    try:
                        attrib_rotate_old = attributes_old["rotate"]
                    except (Exception,):
                       attrib_rotate_old = []

                    try:
                        attrib_translate_old = attributes_old["translate"]
                    except (Exception,):
                        attrib_translate_old = []

                    try:
                        attrib_scale_old = attributes_old["scale"]
                    except (Exception,):
                        attrib_scale_old = []

                    ####### APPEND ALL CURVE LISTS INTO A "db_time_value_data_rotate" GLOBAL LIST
                    if attrib_rotate_old:
                        for items_old in attrib_rotate_old:
                            #print(items_old)
                            if 'curve' in items_old:
                                #print(dict_old['curve'])
                                if items_old['curve'] != 'stepped':
                                    #print(dict_old['curve'])
                                    # Get the original DB Vector Coordinates
                                    db_time_value_data_rotate.append(items_old['curve'])

                    if attrib_translate_old:
                        #print(attrib_translate_old[0]['curve'])
                        # The last time key frame doesn't have associated curve value. We need this to make calc later
                        # So I created a temp var that stores the ini curve of each animation
                        # At the bottom we will insert each curve value at the end of each animation
                        #print(attrib_translate_old[0])
                        # Get the list of 'easies' of Dragonbones, excluding the 'stepped' curves
                        if 'curve' in attrib_translate_old[0] and isinstance(attrib_translate_old[0]['curve'], list):
                            temp_curve = attrib_translate_old[0]['curve']
                        #print(temp_curve)
                        #print(attrib_translate_old)
                        for items_old in attrib_translate_old:
                            # Create a list of Translate X and Y values to use in future
                            # If there's not X and/or Y value, insert 0
                            #print(items_old)
                            if 'x' in items_old:
                                xy_data.append(items_old['x'])
                            if not 'x' in items_old:
                                xy_data.append(0)
                            if 'y' in items_old:
                                xy_data.append(items_old['y'])
                            if not 'y' in items_old:
                                xy_data.append(0)

                            if 'time' and 'curve' in items_old:
                                # Creating a list of translate times
                                db_time_data_translate.append(items_old['time'])
                                #if items_old['curve'] != 'stepped':
                                if isinstance(items_old['curve'], list):
                                    #print(items_old['curve'])
                                    # Get the original DB Vector Coordinates and put it into a var
                                    db_time_value_data_translate.append(items_old['curve'])
                            if 'time' and not 'curve' in items_old:
                                # The last time key in animation that doesn't have curve
                                db_time_data_translate.append(items_old['time'])
                                db_time_value_data_translate.append(temp_curve)
                    #print(db_time_value_data_translate)

                    if attrib_scale_old:
                        #print(attrib_scale_old[0])
                        #print(temp_curve_scale)
                        for items_old in attrib_scale_old:
                            # Get the list of 'easies' of Dragonbones, excluding the 'stepped' curves
                            if 'curve' in items_old:
                                if items_old['curve'] != 'stepped':
                                    #print(items_old)
                                    # if isinstance(attrib_scale_old[0]['curve'], list):
                                    db_time_value_data_scale.append(items_old['curve'])

                            # Create a list of Scale X and Y values to use in future
                            # If there's not X and/or Y value, insert 0
                            #print(items_old)
                            if 'x' in items_old:
                                xy_data_scale.append(items_old['x'])
                            if not 'x' in items_old:
                                xy_data_scale.append(0)
                            if 'y' in items_old:
                                xy_data_scale.append(items_old['y'])
                            if not 'y' in items_old:
                                xy_data_scale.append(0)

                            # if 'time' and 'curve' in items_old:
                            #     # Creating a list of scale times
                            #     db_time_data_scale.append(items_old['time'])
                            #     # if items_old['curve'] != 'stepped':
                            #     # if isinstance(items_old['curve'], list):
                            #     #     # print(items_old['curve'])
                            #     #     # Get the original DB Vector Coordinates and put it into a var
                            #     #     db_time_value_data_scale.append(items_old['curve'])

                            #The last time key animation that doesn't have curve
                            if 'time' in items_old:
                                db_time_data_scale.append(items_old['time'])
                                #db_time_value_data_scale.append(temp_curve_scale)

                for slot_key_old in old_temp_json_data["animations"][anim_key_old]["slots"]:
                    #print(slot_key_old)
                    attributes_slots_old = old_temp_json_data["animations"][anim_key_old]["slots"][slot_key_old]
                    #print(attributes_slots_old)
                    for items_old in attributes_slots_old:
                        # Get the list of 'easies' of Dragonbones, excluding the 'stepped' curves
                        #print(items_old)
                        for elements in attributes_slots_old[items_old]:
                            #print(elements)
                            if 'curve' in elements:
                                if elements['curve'] != 'stepped':
                                    #print(items_old)
                                    # if isinstance(attrib_scale_old[0]['curve'], list):
                                    db_time_value_data_slot.append(elements['curve'])

                            #Create a list of color of all slots
                            if 'color' in elements:
                                color_data_slot.append(elements['color'])

                                #Create a list of time of in all slots that has 'color'
                                if 'time' in elements:
                                    db_time_data_slot.append(elements['time'])

            # print(color_data_slot)
            #print(db_time_data_slot, len(db_time_data_slot))
            # print(db_time_value_data_slot)
            #print(db_time_data_translate, db_time_value_data_translate)
            #print(db_time_data_scale)
            #print(db_time_data_scale, db_time_value_data_scale)
            #print(xy_data_scale)
            ##### END ####
            # This part gets the info of curve Vectors from de Old Dragonbones Json and put into a List

            ########################## Loop in Animation Keys #####################################
            for anim_key in temp_json_data["animations"]:
                #print(anim_key)
                # Loop in all Bone Keys
                for bone_key in temp_json_data["animations"][anim_key]["bones"]:
                    #print(bone_key)
                    #print(temp_json_data["animations"][anim_key]["bones"])
                    attributes = temp_json_data["animations"][anim_key]["bones"][bone_key]
                    #print(attributes)

                    #Detecting if there's specific animation attributes in the Json
                    try:
                        attrib_rotate = attributes["rotate"]
                    except (Exception,):
                        attrib_rotate = []

                    try:
                        attrib_translate = attributes["translate"]
                    except (Exception,):
                        attrib_translate = []

                    try:
                        attrib_scale = attributes["scale"]
                    except (Exception,):
                        attrib_scale = []

                    try:
                        # If there, delete all curves in Shear animations and let only the keyframes times
                        for key in attributes['shear']:
                            if 'curve' in key:
                                del key['curve']
                    except:
                        pass


                    """
                     >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> BEGIN OF ROTATE CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    """
                    if attrib_rotate:
                        #print(attrib_rotate)
                        # Replacing all 'angle' keys for 'value'
                        for dict_rot in attrib_rotate:
                            #print(dict)
                            #for keys in dict:
                            if 'angle' in dict_rot.keys():
                                # Replacing all keys 'angle' to 'value' to make rotation works
                                dict_rot['value'] = dict_rot.pop('angle', None)

                            # Changing the order os keys to 'time', 'value', 'curve'
                            if 'curve' in dict_rot:
                                #print(dict)
                                key_dict = list(dict_rot.keys())
                                key_dict[0] = 'time'
                                key_dict[1] = 'value'
                                key_dict[2] = 'curve'
                                # Reorder 'time', 'value' and 'curve'
                                for k in key_dict:
                                    #print(k)
                                    dict_rot[k] = dict_rot.pop(k)
                                #print(dict['curve'])
                        # Create a list with the 'curve' 2 and 3 values to add in the next step
                        for step in range(len(attrib_rotate)):
                            # print(step)
                            if step < len(attrib_rotate) - 1: # Jump the last key, because it doesn't have curve
                                # If is there 3 arguments ('time', 'value' and 'curve') continues
                                if len(attrib_rotate[step]) >= 3:
                                    # If there's stepped curve, the script ignores
                                    if attrib_rotate[step]['curve'] != 'stepped':
                                        #print(attrib_rotate[step]['curve'])
                                        jump = step + 1
                                        #print(jump)
                                        next_time = attrib_rotate[jump]['time']
                                        next_value = attrib_rotate[jump]['value']
                                        #print(next_time, next_value)
                                        time_value_data_rotate.append(next_time)
                                        time_value_data_rotate.append(next_value)

                                # If is there only 2 values ('time' and 'value' ONLY, JUMP to next value)
                                # elif len(attrib_rotate[step]) <= 2:
                                #     jump = step + 1

                        for k in attrib_rotate:
                            #print(k.keys())
                            #Apply the actual 'time' and 'value' in the first two items (time1, value1) in the list 'curve'
                            if 'curve' in k:
                                #print(k)
                                # The script ignores the stepped curve
                                if k['curve'] != 'stepped':
                                    #print(k['curve'])
                                    k['curve'][0] = k['time']
                                    k['curve'][1] = k['value']

                        for val in attrib_rotate:
                            if len(val) >= 3:
                                #print(val)
                            # Apply the actual 'time' and 'value' in the last two items (time2, value2) in the list 'curve'
                                if 'curve' in val:
                                    # The script ignores the stepped curve
                                    if val['curve'] != 'stepped':
                                        #print(val['curve'])
                                        val['curve'][2] = time_value_data_rotate[step_curve]
                                        step_curve += 1
                                        val['curve'][3] = time_value_data_rotate[step_curve]
                                        step_curve += 1

                        #Apply a Function to calculate the Bézier curve from the Old Dragonbones Vector List
                        for element_dict in attrib_rotate:
                            #print(element_dict)
                            if 'curve' in element_dict:
                                if element_dict['curve'] != 'stepped':
                                    counter += 1
                                    # print(counter - 1)
                                    #print(element_dict['curve'])
                                    #print(db_time_value_data_rotate[counter - 1])
                                    for values in range(0, 4):
                                        #print(values)
                                        if values == 0: # Time 1
                                            # The format of Rotate is [time1, value1(angle1), time2, value2(angle2)]
                                            # For each curve gets the correspondent value to make calculations and change
                                            # Create temp vars to store the original values
                                            ini_value = element_dict['curve'][values]
                                            # Get the original value to calc later
                                            ini_value_original = element_dict['curve'][values]
                                            last_value = element_dict['curve'][values + 2]
                                            vector = db_time_value_data_rotate[counter - 1][values]
                                            #print(ini_value, last_value, vector)
                                            element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                ini_value, last_value, vector)

                                        if values == 1: # Value1
                                            ini_value = element_dict['curve'][values]
                                            last_value = element_dict['curve'][values + 2]
                                            vector = db_time_value_data_rotate[counter - 1][values]
                                            element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                ini_value, last_value, vector)

                                        if values == 2: # Time2
                                            #ini_value_original = element_dict['curve'][values - 2]
                                            last_value = element_dict['curve'][values]
                                            vector = db_time_value_data_rotate[counter - 1][values]
                                            # Use the original value to correct curve calculation
                                            element_dict['curve'][values] = bezier_curve_calc_end_values_x(
                                                ini_value_original, last_value, vector)

                                        if values == 3: # Value 2
                                            last_value = element_dict['curve'][values]
                                            vector = db_time_value_data_rotate[counter - 1][values]
                                            element_dict['curve'][values] = bezier_curve_calc_end_values_y(
                                                last_value, vector)
                    # print(db_time_value_data_rotate)
                    # print(time_value_data_rotate)
                    # print(attrib_rotate)

                    """
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END OF ROTATE CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    """

                    """
                    # >>>>>>>>>>>>>>>>>>>>>>>>>>> BEGIN OF TRANSLATE CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    """
                    if attrib_translate:
                        # Reorder the key attributes
                        for dictx in attrib_translate:
                            #print(dict)
                            # Changing the order os keys to 'time', 'x', 'y' and 'curve'
                            key_dict = list(dictx.keys())
                            #print(key_dict, len(key_dict))
                            if len(key_dict) == 4:
                                key_dict[0] = 'time'
                                key_dict[1] = 'x'
                                key_dict[2] = 'y'
                                key_dict[3] = 'curve'

                            if len(key_dict) == 3:
                                key_dict[0] = 'time'
                                if 'x' and not 'y' in dictx.keys():
                                    key_dict[1] = 'x'
                                if 'y' and not 'x' in dictx.keys():
                                    key_dict[1] = 'y'
                                if 'y' and 'x' in dictx.keys():
                                    key_dict[1] = 'x'
                                    key_dict[2] = 'y'
                                if 'curve' in dictx.keys():
                                    key_dict[2] = 'curve'

                            if len(key_dict) == 2:
                                key_dict[0] = 'time'
                                if 'x' in dictx.keys():
                                    key_dict[1] = 'x'
                                if 'y' in dictx.keys():
                                    key_dict[1] = 'y'
                                if 'curve' in dictx.keys():
                                    key_dict[1] = 'curve'

                            for k in key_dict:
                                dictx[k] = dictx.pop(k)
                                # print(k)

                            # Add 4 more items in list 'curve'
                            try:
                                if dictx['curve'] != 'stepped':
                                    if 'curve' in dictx:
                                        # Add 4 more items in each 'curve' to use later. I choose 999 to be more visible.
                                        dictx['curve'].append(999)
                                        dictx['curve'].append(999)
                                        dictx['curve'].append(999)
                                        dictx['curve'].append(999)

                                    # Add initial time1 to the positions 0 and 4 of the curve list
                                        dictx['curve'][0] = dictx['time']
                                        dictx['curve'][4] = dictx['time']
                            except (Exception,):
                                pass

                            #print(key_dict)
                            #print(dict)
                            # Get initial x1 and y1 values if there's x or y values. If not, they are 0.
                            if len(key_dict) == 4:  # There time, curve, x and y
                                # Use this to get 'curve' that has a list, not "stepped"
                                if isinstance(dictx['curve'], list):
                                    dictx['curve'][1] = dictx['x']
                                    dictx['curve'][5] = dictx['y']

                            if len(key_dict) == 3: # There time and/or curve and/or x and/or y
                                try:
                                    if isinstance(dictx['curve'], list):
                                        if 'x' in dictx:
                                            dictx['curve'][1] = dictx['x']
                                        else:
                                            dictx['curve'][1] = 0
                                        if 'y' in dictx:
                                            #if 'curve' in dict:
                                            dictx['curve'][5] = dictx['y']
                                        else:
                                            dictx['curve'][5] = 0
                                except (Exception,):
                                    pass

                            if len(key_dict) == 2: # There only time plus curve or x or y
                                try:
                                    if isinstance(dictx['curve'], list):
                                        #If not x or y, the x and y initial values in curve are 0.
                                        dictx['curve'][1] = 0
                                        dictx['curve'][5] = 0
                                except (Exception,):
                                    pass
                            #print(dict)
                        #print(attrib_translate)
                        # Add time2 to the specific positions( 2 and 6) of the list
                        for d in attrib_translate:
                            #print(d)
                            if 'curve' in d:
                                if isinstance(d['curve'], list):
                                    #print(d['curve'], time_counter, db_time_data_translate[time_counter + 1])
                                    #print(db_time_data_translate)
                                    d['curve'][2] = db_time_data_translate[time_counter + 1]
                                    d['curve'][6] = db_time_data_translate[time_counter + 1]
                            if 'time' in d:
                                time_counter += 1
                        #print('xy data', xy_data)
                        for item in attrib_translate:
                            #print(item)
                            if item['time'] == 0: # If the script reaches the first item in the list, jump 2
                                #print(item)
                                time_counter_xy += 2
                            # If the first item doesn't have curve, jump 2
                            if item['time'] == 0 and not 'curve' in item:
                                time_counter_xy += 2

                            # If there's curve in an item, proceed with the insert o data
                            if 'curve' in item:
                                # if the curve is a list, insert items
                                if isinstance(item['curve'], list):
                                    item['curve'][3] = xy_data[time_counter_xy]
                                    time_counter_xy += 1
                                    item['curve'][7] = xy_data[time_counter_xy]
                                    time_counter_xy += 1
                                    #print(xy_data[time_counter_xy], time_counter_xy)

                                # If there's a "stepped" curve, jump 2
                                if isinstance(item['curve'], str):
                                    time_counter_xy += 2

                            # If there's keyframes that doesn't have curves list, and they don't locate in the
                            # beginning or the last keyframe, jump 2
                            if not 'curve' in item and item['time'] != 0 and item != attrib_translate[-1]:
                                #print(item)
                                time_counter_xy += 2
                                # print(time_counter_xy)
                                # print(xy_data)
                                #print(type(item['curve']))
                            #print(item)

                        # The Translation Curve format is: [time1, x1, time2, x2, time1, y1, time2, y2]
                        # Apply a Function to calculate the Bézier curve from the Old Dragonbones Vector List
                        for element_dict in attrib_translate:
                            #print(element_dict)
                            if 'curve' in element_dict:
                                if isinstance(element_dict['curve'], list): # Using element_dict != 'stepped'
                                    counter_translate += 1
                                    #print(counter_translate - 1)
                                    #print(element_dict['curve'])
                                    #print(db_time_value_data_translate)
                                    for values in range(0, 8):
                                        #print(values)
                                        if isinstance(db_time_value_data_translate, list):
                                            if values == 0:  # Time1

                                                #print(element_dict)
                                                ini_value = element_dict['curve'][values]
                                                # Get the original value to use later
                                                ini_value_original_x = element_dict['curve'][values]
                                                last_value = element_dict['curve'][values + 2]
                                                vector = db_time_value_data_translate[counter_translate - 1][values]
                                                #print(db_time_value_data_translate)
                                                #print(type(ini_value), type(last_value), type(vector))
                                                #print(ini_value, last_value, vector)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value, last_value, vector)
                                                #print(db_time_value_data_translate[counter][values])

                                            if values == 1:  # X1
                                                ini_value = element_dict['curve'][values]
                                                last_value = element_dict['curve'][values + 2]
                                                vector = db_time_value_data_translate[counter_translate - 1][values]
                                                #print(ini_value, last_value, vector)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value, last_value, vector)

                                            if values == 2: # Time2
                                                #print(element_dict)
                                                #ini_value = element_dict['curve'][values - 2]
                                                last_value = element_dict['curve'][values]
                                                vector = db_time_value_data_translate[counter_translate - 1][values]
                                                #print(ini_value, last_value, vector)
                                                # Use the original value to correct curve calculation
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_x(
                                                    ini_value_original_x, last_value, vector)

                                            if values == 3: # X2
                                                last_value = element_dict['curve'][values]
                                                vector = db_time_value_data_translate[counter_translate - 1][values]
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_y(
                                                    last_value, vector)

                                            # As db_time_value_data_translate curve has only 4 values,
                                            # we begin values from 0
                                            if values == 4:  # Time1 --Get 0
                                                ini_value = element_dict['curve'][values]
                                                ini_value_original_y = element_dict['curve'][values]
                                                last_value = element_dict['curve'][values + 2]
                                                vector = db_time_value_data_translate[counter_translate
                                                                                      - 1][values - values]
                                                #print(ini_value, last_value, vector)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value, last_value, vector)

                                            if values == 5:  # Y1 - -Get 1
                                                ini_value = element_dict['curve'][values]
                                                last_value = element_dict['curve'][values + 2]
                                                vector = db_time_value_data_translate[counter_translate
                                                                                      - 1][values - values + 1]
                                                #print(ini_value, last_value, vector)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value, last_value, vector)

                                            if values == 6:  # Time2 - - Get 2
                                                #ini_value = element_dict['curve'][values - 2]
                                                last_value = element_dict['curve'][values]
                                                vector = db_time_value_data_translate[counter_translate
                                                                                      - 1][values - values + 2]
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_x(
                                                    ini_value_original_y, last_value, vector)

                                            if values == 7:  # Y2 - - Get 3
                                                last_value = element_dict['curve'][values]
                                                vector = db_time_value_data_translate[counter_translate
                                                                                      - 1][values - values + 3]
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_y(
                                                    last_value, vector)

                    """
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END OF TRANSLATE CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    """

                    """
                    # >>>>>>>>>>>>>>>>>>>>>>>>>>> BEGIN OF SCALE CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    """
                    #print(attrib_scale)
                    if attrib_scale:
                        # Reorder the key attributes
                        for dict_sc in attrib_scale:
                            # print(dict)
                            # Changing the order os keys to 'time', 'x', 'y' and 'curve'
                            key_dict = list(dict_sc.keys())
                            # print(key_dict, len(key_dict))
                            if len(key_dict) == 4:
                                key_dict[0] = 'time'
                                key_dict[1] = 'x'
                                key_dict[2] = 'y'
                                key_dict[3] = 'curve'

                            if len(key_dict) == 3:
                                # The first key is time
                                key_dict[0] = 'time'
                                if 'x' and not 'y' in dict_sc.keys():
                                    key_dict[1] = 'x'
                                if 'y' and not 'x' in dict_sc.keys():
                                    key_dict[1] = 'y'
                                if 'y' and 'x' in dict_sc.keys():
                                    key_dict[1] = 'x'
                                    key_dict[2] = 'y'
                                if 'curve' in dict_sc.keys():
                                    key_dict[2] = 'curve'

                            if len(key_dict) == 2:
                                key_dict[0] = 'time'
                                if 'x' in dict_sc.keys():
                                    key_dict[1] = 'x'
                                if 'y' in dict_sc.keys():
                                    key_dict[1] = 'y'
                                if 'curve' in dict_sc.keys():
                                    key_dict[1] = 'curve'

                            for k in key_dict:
                                dict_sc[k] = dict_sc.pop(k)
                                # print(k)

                            # If there's curve in key, add 4 more items in list 'curve'
                            try:
                                if dict_sc['curve'] != 'stepped':
                                    if 'curve' in dict_sc:
                                        # Add 4 more items in each 'curve' to use later. I choose 999 to be more visible.
                                        dict_sc['curve'].append(999)
                                        dict_sc['curve'].append(999)
                                        dict_sc['curve'].append(999)
                                        dict_sc['curve'].append(999)

                                        # Add initial time1 to the positions 0 and 4 of the curve list
                                        dict_sc['curve'][0] = dict_sc['time']
                                        dict_sc['curve'][4] = dict_sc['time']
                            except (Exception,):
                                pass

                            # print(key_dict)
                            # print(dict)
                            # Get initial x1 and y1 values if there's x or y values. If not, they are 0.
                            if len(key_dict) == 4:  # There time, curve, x and y
                                # Use this to get 'curve' that has a list, not "stepped"
                                if isinstance(dict_sc['curve'], list):
                                    dict_sc['curve'][1] = dict_sc['x']
                                    dict_sc['curve'][5] = dict_sc['y']

                            if len(key_dict) == 3:  # There time and/or curve and/or x and/or y
                                # If key_dict has time, x and y:
                                if key_dict == ['time', 'x', 'y']:
                                    pass
                                # If not apply anothe configuration
                                else:
                                    try:
                                        if isinstance(dict_sc['curve'], list):
                                            if 'x' in dict_sc:
                                                dict_sc['curve'][1] = dict_sc['x']
                                            else:
                                                dict_sc['curve'][1] = 0
                                            if 'y' in dict_sc:
                                                # if 'curve' in dict:
                                                dict_sc['curve'][5] = dict_sc['y']
                                            else:
                                                dict_sc['curve'][5] = 0
                                    except (Exception,):
                                        #print("Error Generate Key 3", key_dict)
                                        pass

                            if len(key_dict) == 2:  # There only time plus curve or x or y
                                try:
                                    if isinstance(dict_sc['curve'], list):
                                        # If not x or y, the x and y initial values in curve are 0.
                                        dict_sc['curve'][1] = 0
                                        dict_sc['curve'][5] = 0
                                except (Exception,):
                                    #print("Error Generate Key 2", key_dict)
                                    pass
                            # print(dict)
                        # print(attrib_scale)
                        # Add time2 to the specific positions( 2 and 6) of the list
                        for d in attrib_scale:
                            #print(d)
                            if 'curve' in d:
                                if isinstance(d['curve'], list):
                                    # if 'curve' in attrib_scale[step_scale] != 'stepped':
                                    # print(d['curve'], time_counter, db_time_data_scale[time_counter_scale + 1])
                                    # print(db_time_data_scale)
                                    d['curve'][2] = db_time_data_scale[time_counter_scale + 1]
                                    d['curve'][6] = db_time_data_scale[time_counter_scale + 1]
                            if 'time' in d:
                                time_counter_scale += 1
                        # print('xy data', xy_data)
                        for item in attrib_scale:
                            #print(item)
                            if item['time'] == 0:  # If the script reaches the first item in the list, jump 2
                                # print(item)
                                time_counter_xy_scale += 2
                            # If the first item doesn't have curve, jump 2
                            if item['time'] == 0 and not 'curve' in item:
                                time_counter_xy_scale += 2

                            # If there's curve in an item, proceed with the insert data
                            if 'curve' in item:
                                # if the curve is a list, insert items
                                if isinstance(item['curve'], list):
                                    item['curve'][3] = xy_data_scale[time_counter_xy_scale]
                                    time_counter_xy_scale += 1
                                    item['curve'][7] = xy_data_scale[time_counter_xy_scale]
                                    time_counter_xy_scale += 1
                                    # print(xy_data[time_counter_xy], time_counter_xy)

                                # If there's a "stepped" curve, jump 2
                                if isinstance(item['curve'], str):
                                    time_counter_xy_scale += 2

                            # If there's keyframes that doesn't have curves list, and they don't locate in the
                            # beginning or the last keyframe, jump 2
                            if not 'curve' in item and item['time'] != 0 and item != attrib_scale[-1]:
                                # print(item)
                                time_counter_xy_scale += 2
                                # print(time_counter_xy)
                                # print(xy_data)
                                # print(type(item['curve']))
                            #print(item)
                        #print(attrib_scale)
                        # The Scale Curve format is: [time1, x1, time2, x2, time1, y1, time2, y2]
                        # Apply a Function to calculate the Bézier curve from the Old Dragonbones Vector List
                        for element_dict in attrib_scale:
                            #print(element_dict)
                            if 'curve' in element_dict:
                                if isinstance(element_dict['curve'], list):  # Using element_dict != 'stepped'
                                    counter_scale += 1
                                    # print(counter_scale - 1)
                                    # print(element_dict['curve'])
                                    #print(db_time_value_data_scale)
                                    for values in range(0, 8):
                                        #print(values)
                                        if isinstance(db_time_value_data_scale, list):
                                            if values == 0:  # Time1
                                                #print(element_dict)
                                                ini_value_scale = element_dict['curve'][values]
                                                # Get the original value to use later
                                                ini_value_original_x_scale = element_dict['curve'][values]
                                                last_value_scale = element_dict['curve'][values + 2]
                                                vector_scale = db_time_value_data_scale[counter_scale - 1][values]
                                                #print(vector_scale)
                                                # print(db_time_value_data_scale)
                                                # print(type(ini_value), type(last_value), type(vector))
                                                #print(ini_value, last_value, vector_scale)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value_scale, last_value_scale, vector_scale)
                                                # print(db_time_value_data_scale[counter][values])

                                            if values == 1:  # X1
                                                ini_value_scale = element_dict['curve'][values]
                                                last_value_scale = element_dict['curve'][values + 2]
                                                vector_scale = db_time_value_data_scale[counter_scale - 1][values]
                                                #print(ini_value, last_value, vector_scale)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value_scale, last_value_scale, vector_scale)

                                            if values == 2:  # Time2
                                                # print(element_dict)
                                                # ini_value = element_dict['curve'][values - 2]
                                                last_value_scale = element_dict['curve'][values]
                                                vector_scale = db_time_value_data_scale[counter_scale - 1][values]
                                                #print(ini_value, last_value, vector_scale)
                                                # Use the original value to correct curve calculation
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_x(
                                                    ini_value_original_x_scale, last_value_scale, vector_scale)

                                            if values == 3:  # X2
                                                last_value_scale = element_dict['curve'][values]
                                                vector_scale = db_time_value_data_scale[counter_scale - 1][values]
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_y(
                                                    last_value_scale, vector_scale)
                                                #print(ini_value, last_value, vector_scale)

                                            # As db_time_value_data_scale curve has only 4 values, we begin values from 0
                                            if values == 4:  # Time1 --Get 0
                                                ini_value_scale = element_dict['curve'][values]
                                                ini_value_original_y_scale = element_dict['curve'][values]
                                                last_value_scale = element_dict['curve'][values + 2]
                                                vector_scale = db_time_value_data_scale[counter_scale
                                                                                        - 1][values - values]
                                                # print(ini_value, last_value, vector)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value_scale, last_value_scale, vector_scale)

                                            if values == 5:  # Y1 - -Get 1
                                                ini_value_scale = element_dict['curve'][values]
                                                last_value_scale = element_dict['curve'][values + 2]
                                                vector_scale = db_time_value_data_scale[counter_scale
                                                                                        - 1][values - values + 1]
                                                # print(ini_value, last_value, vector)
                                                element_dict['curve'][values] = bezier_curve_calc_begin_values(
                                                    ini_value_scale, last_value_scale, vector_scale)

                                            if values == 6:  # Time2 - - Get 2
                                                # ini_value = element_dict['curve'][values - 2]
                                                last_value_scale = element_dict['curve'][values]
                                                vector_scale = db_time_value_data_scale[counter_scale
                                                                                        - 1][values - values + 2]
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_x(
                                                    ini_value_original_y_scale, last_value_scale, vector_scale)

                                            if values == 7:  # Y2 - - Get 3
                                                last_value_scale = element_dict['curve'][values]
                                                vector_scale = db_time_value_data_scale[counter_scale
                                                                                        - 1][values - values + 3]
                                                element_dict['curve'][values] = bezier_curve_calc_end_values_y(
                                                    last_value_scale, vector_scale)

                    """
                    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END OF SCALE CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                    """

                """
                >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> BEGIN OF SLOT COLOR CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                """
                # Loop in all Slot Keys
                slot_color_list = []
                slot_time_list = []


                for slot_key in temp_json_data["animations"][anim_key]["slots"]:
                    #print(slot_key)
                    attributes_slots = temp_json_data["animations"][anim_key]["slots"][slot_key]
                    #print(attributes_slots)
                    try:
                        attrib_slot_color = attributes_slots['rgba']
                        #print(attrib_slot_color)
                        # # If there, delete all curves in rgba animations and let only the keyframes times
                        # for key in attributes_slots['rgba']:
                        #     if 'curve' in key:
                        #         del key['curve']
                    except (Exception,):
                        attrib_slot_color = []

                    if attrib_slot_color:
                        for dict_sl in attrib_slot_color:
                            #print(dict_sl)
                            try:
                                if dict_sl['curve'] != 'stepped':
                                    if 'curve' in dict_sl:
                                        for sl in range(12):
                                            #Add 12 more items in each 'curve' to use later.
                                            # I choose 999 to be more visible.
                                            dict_sl['curve'].append(999)

                            except (Exception,):
                                pass

                        # Create a new color rgba curve list, with the following pattern:
                        # [rx1, ry1, rx2, ry2, gx1, gy1, gx2, gy2, bx1, by1, bx2, by2, ax1, ay1, ax2, ay2]
                        #   0    1    2    3    4    5    6    7    8    9    10   11   12   13   14   15
                        # Where "x" is the Time vector Bézier end "y" is the color channel intensity (0 to 1).

                        for d in attrib_slot_color:
                            #print(d)
                            if 'curve' in d:
                                # print(d)
                                if isinstance(d['curve'], list):
                                    # Add Time ini in positions 0, 4, 8 and 12 of curve list
                                    #print(d['time'])
                                    time_x_ini = d['time']
                                    for t in range(0, 13, 4):
                                        d['curve'][t] = time_x_ini

                                    # Add rgba ini color to positions 1, 5, 9 and 13 in curve list
                                    #print(d['color'])
                                    #rgba calculation
                                    rgba_hex = d['color']
                                    r_color = round((int(rgba_hex[0:2], 16)/255), 2)
                                    g_color = round((int(rgba_hex[2:4], 16)/255), 2)
                                    b_color = round((int(rgba_hex[4:6], 16)/255), 2)
                                    a_color = round((int(rgba_hex[6:8], 16)/255), 2)
                                    #print(r_color, g_color, b_color, a_color)
                                    d['curve'][1] = r_color
                                    d['curve'][5] = g_color
                                    d['curve'][9] = b_color
                                    d['curve'][13] = a_color

                                    rgba_hex2 = color_data_slot[time_counter_slot_color + 1]
                                    r_color2 = round((int(rgba_hex2[0:2], 16) / 255), 2)
                                    g_color2 = round((int(rgba_hex2[2:4], 16) / 255), 2)
                                    b_color2 = round((int(rgba_hex2[4:6], 16) / 255), 2)
                                    a_color2 = round((int(rgba_hex2[6:8], 16) / 255), 2)

                                    d['curve'][3] = r_color2
                                    d['curve'][7] = g_color2
                                    d['curve'][11] = b_color2
                                    d['curve'][15] = a_color2
                                    #print(r_color2, g_color2, b_color2, a_color2)
                                    # print(time_counter_slot_color)
                                    # print(color_data_slot[time_counter_slot_color + 1])

                                    # Get the time of every key after the actual key
                                    time_x_after = db_time_data_slot[time_counter_slot_color + 1]
                                    # Add the final time in curve list into positions 2, 6, 10, 14
                                    d['curve'][2] = time_x_after
                                    d['curve'][6] = time_x_after
                                    d['curve'][10] = time_x_after
                                    d['curve'][14] = time_x_after
                                    #print(time_x_after)
                            time_counter_slot_color += 1

                        # Calculate curves using the bezier formula
                        #print(attrib_slot_color)
                        new_curve = []
                        for c in attrib_slot_color:
                            if 'curve' in c:
                                # print(d)
                                if isinstance(c['curve'], list):
                                    #print(c['curve'])
                                    #print(db_time_value_data_slot[time_counter_curve_color])
                                    # [0.5, 0, 0.5, 1]
                                    #print(bezier_curve_calc_begin_values(c['curve'][0], c['curve'][2],
                                                                         #db_time_value_data_slot[time_counter_curve_color][0]))
                                    # Calculation Curve for Red Channel
                                    c['curve'][0] = round(bezier_curve_calc_begin_values(c['curve'][0], c['curve'][2],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             0]), 2)

                                    c['curve'][1] = round(bezier_curve_calc_begin_values(c['curve'][1], c['curve'][3],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             0]), 2)

                                    c['curve'][2] = round(bezier_curve_calc_end_values_x(c['curve'][0], c['curve'][2],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             2]), 2)

                                    c['curve'][3] = round(bezier_curve_calc_end_values_x(c['curve'][1], c['curve'][3],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             2]), 2)

                                    # Calculation Curve for Green Channel
                                    c['curve'][4] = round(bezier_curve_calc_begin_values(c['curve'][4], c['curve'][6],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             0]), 2)

                                    c['curve'][5] = round(bezier_curve_calc_begin_values(c['curve'][5], c['curve'][7],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             0]), 2)

                                    c['curve'][6] = round(bezier_curve_calc_end_values_x(c['curve'][4], c['curve'][6],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             2]), 2)

                                    c['curve'][7] = round(bezier_curve_calc_end_values_x(c['curve'][5], c['curve'][7],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             2]), 2)
                                    # Calculation Curve for Blue Channel
                                    c['curve'][8] = round(bezier_curve_calc_begin_values(c['curve'][8], c['curve'][10],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             0]), 2)

                                    c['curve'][9] = round(bezier_curve_calc_begin_values(c['curve'][9], c['curve'][11],
                                                                                         db_time_value_data_slot[
                                                                                             time_counter_curve_color][
                                                                                             0]), 2)

                                    c['curve'][10] = round(bezier_curve_calc_end_values_x(c['curve'][8], c['curve'][10],
                                                                                          db_time_value_data_slot[
                                                                                              time_counter_curve_color][
                                                                                              2]), 2)

                                    c['curve'][11] = round(bezier_curve_calc_end_values_x(c['curve'][9], c['curve'][11],
                                                                                          db_time_value_data_slot[
                                                                                              time_counter_curve_color][
                                                                                              2]), 2)
                                    # Calculation Curve for Alpha Channel
                                    c['curve'][12] = round(
                                        bezier_curve_calc_begin_values(c['curve'][12], c['curve'][14],
                                                                       db_time_value_data_slot[
                                                                           time_counter_curve_color][
                                                                           0]), 2)

                                    c['curve'][13] = round(
                                        bezier_curve_calc_begin_values(c['curve'][13], c['curve'][15],
                                                                       db_time_value_data_slot[
                                                                           time_counter_curve_color][
                                                                           0]), 2)

                                    c['curve'][14] = round(
                                        bezier_curve_calc_end_values_x(c['curve'][12], c['curve'][14],
                                                                       db_time_value_data_slot[
                                                                           time_counter_curve_color][
                                                                           2]), 2)

                                    c['curve'][15] = round(
                                        bezier_curve_calc_end_values_x(c['curve'][13], c['curve'][15],
                                                                       db_time_value_data_slot[
                                                                           time_counter_curve_color][
                                                                           2]), 2)

                                    time_counter_curve_color += 1


                """
                >>>>>>>>>>>>>>>>>>>>>>>>>>>>>> END OF SLOT COLOR CURVE CALCULATION <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
                """


        """
        ######################################## END OF CURVE#############################################
        """

        """
        ############################### BEGIN OF LINEAR SECTION #############################################
        """

        if self.easing_type == 'linear':
            #print("Easy Type: Linear")
            try:
                for anim_key in temp_json_data["animations"]:
                    for bone_key in temp_json_data["animations"][anim_key]["bones"]:
                        #print(json_data["animations"][anim_key]["bones"][bone_key])
                        attributes = temp_json_data["animations"][anim_key]["bones"][bone_key]
                        #print(attributes)
                        for items in attributes.values():
                            #print(items)
                            for dictionary in items:
                                # print(dict)
                                if 'curve' in dictionary.keys():
                                    del dictionary['curve']  # Delete all 'curve' attributes, making animations linear.
                                    # print(dict)
                                # Replacing all keys 'angle' to 'value' to make rotations works
                                if 'angle' in dictionary:
                                    dictionary['value'] = dictionary.pop('angle', None)

                    for slot_key in temp_json_data["animations"][anim_key]["slots"]:
                        #print(slot_key)
                        attributes_slots = temp_json_data["animations"][anim_key]["slots"][slot_key]
                        #print(attributes_slots)
                        for items in attributes_slots.values():
                            #print(items)
                            for elements in items:
                                if 'curve' in elements.keys():
                                    del elements['curve']
            except:
                pass

        """
        ################################## END OF LINEAR SECTION #############################################
        """
        """
        ################################## END OF ANIMATIONS ##################################################
        """
        """
        ################################# BEGIN OF FILE SAVE ######################################################
        """
        # Copy the Temp Json back to the Json Data
        json_data = temp_json_data

        # Convert final Json file to Pretty JSON and save it with new extension (.json or .spinejson).
        converted = json.dumps(json_data, indent=4)

        # Creating new filename with new extension from old json file
        new_json_file_name = self.new_json_file

        # print(new_json_file_name)

        # If there's a diferent folder to save new .json and "Copy Textures Folder" is marked then make a copy
        #print("Texture folder Copy Status:", self.copy_textures_folder)
        if self.copy_textures_folder:
            source_folder = Path(self.old_json_file_name)
            source_directory = os.path.dirname(source_folder)
            textures_folder_path = os.path.dirname(source_folder) + "/" + source_folder.stem + "_texture"
            textures_folder_name = source_folder.stem + "_texture"

            destination_file = Path(self.new_json_file)
            destination_folder = os.path.dirname(destination_file)

            folder_name = destination_folder + "/" + textures_folder_name
            # print(destination_folder)
            # print(source_directory)
            # Copy Textures folder IF the Input and Output directories are different
            # This is only for Command Line because this test is done by the GUI.
            if source_folder == source_directory:
                pass
                #print("Same Textures Folder Directory - Skipping copy")
            else:
                #print("different directory")
                # Create a new Texture folder in the output directory
                try:
                    os.mkdir(folder_name)
                    # print(f"Folder '{folder_name}' created successfully.")
                except FileExistsError:
                    pass
                    # print(f"Folder '{folder_name}' already exists.")
                except Exception as e:
                    pass
                    #print(f"An error occurred: {e}")

            # Copy the content of original Texture folder inside the new folder, in the same output directory
            shutil.copytree(textures_folder_path, folder_name, dirs_exist_ok=True)
            #print(f"Copied contents of '{textures_folder_path}' to '{folder_name}'.")

        # Generate a new .json or .spinejson file in the same folder of db_reborn
        with open(new_json_file_name, 'w') as file:
            file.write(converted)

        self.file_converted = True

        # If using command line, the app print this output message
        if len(sys.argv) > 1:
            print("Conversion Done!")
        """
        ################################# END OF FILE SAVE ######################################################
        """

"""
###################################### END OF SCRIPT PROCESS #############################################
"""

"""
################################# BEGIN OF ENTER THE SCRIPT ##################################################
"""

if __name__ == "__main__":
    # If "linear", the script will erase all 'curve' dicts and put all animations linear to prevent crashes.
    # If "curve", the script will convert the Dragonbones "easing" ('curve': [0, 0, 0.5, 1])
    # to the format of Spine ('curve': [frame1, value1, frame2, value2]) in case of 'angle'.
    # In case of 'translate' and 'scale' there are the double of values: x and y
    # ('curve': [frame1, value_x1, frame2, value_x2, frame1, value_y1, frame2, value_y2])
    # In case of 'shear', Dragonbones doesn't have this feature in its editor and generates automatically
    # 'curves' in some cases without user control. As we cannot specify values for x and y Shear as Spine does and
    # shear effect is not so important to the animation, I decided to erase all Shear curves from the 'spinejson' file.

    # Using arguments in command line
    old_json_path = sys.argv[1] # Using the command line argument
    new_file_path = sys.argv[2] # Using the command line argument
    sp_version = sys.argv[3] # Using the command line argument: "4.2.22"
    easing = sys.argv[4] # Argument "linear" or "curve"
    copy_textures_folder = sys.argv[5] # Argument to copy Textures folder to a new folder
    # app_dir = os.path.dirname(__file__)
    DbJsonConverter(old_json_path, new_file_path, sp_version, easing, copy_textures_folder)

"""
################################# END OF ENTER THE SCRIPT ######################################################
"""


